(ns legalsupport.datoms
  "Emit `data/jurisdiction-rules.datoms.edn` — a flat, transactable
  projection of `legalsupport.facts` for the superproject's DataScript
  query plane (`manifest/edn-query.cljs`, ADR-2607171600 / 2607252000).

  The file is GENERATED, never hand-edited: `legalsupport.facts` is the
  single source of truth and a hand-edit would silently desynchronise
  the queryable copy from the copy the governor actually enforces.
  Regenerate with:

      clojure -M:emit-datoms

  Shape follows the plane's conventions: one entity per fact, scalar
  values only, collections `pr-str`-ed into string blobs, and
  `:source/dataset \"legal-jurisdiction-rules\"` so results can be told
  apart from the other datasets sharing the plane."
  (:require [clojure.java.io :as io]
            [clojure.pprint :as pp]
            [kotoba.lang.text :as str]
            [legalsupport.facts :as facts]))

(def ^:private out-path "data/jurisdiction-rules.datoms.edn")

(def ^:private dataset "legal-jurisdiction-rules")

(defn- kw->s [k] (when k (subs (str k) 1)))

(defn- rule-entities [id jid]
  (for [r (facts/rules jid)]
    (cond-> {:db/id (id)
             :source/dataset dataset
             :legal/fact-kind "rule"
             :legal/jurisdiction jid
             :legal/rule-id (:rule/id r)
             :legal/rule-title (:rule/title r)
             :legal/url (:rule/url r)
             :legal/url-provenance (kw->s (:rule/url-provenance r))
             :legal/verification (kw->s (:rule/verification r))
             :legal/verified (boolean (facts/verified-rule? r))
             :legal/retrieved-at (:rule/retrieved-at r)}
      (:rule/instrument r) (assoc :legal/instrument (:rule/instrument r))
      (:rule/established-date r) (assoc :legal/established-date (:rule/established-date r))
      (:rule/quote r) (assoc :legal/quote (:rule/quote r))
      (:rule/summary r) (assoc :legal/summary (:rule/summary r))
      (:rule/verification-note r) (assoc :legal/verification-note (:rule/verification-note r))
      ;; 拘束力は検証水準とは別の問い。モデル規則は原典を読んでも法ではない。
      (:rule/binding-force r) (assoc :legal/binding-force (kw->s (:rule/binding-force r)))
      (seq (:rule/topic r)) (assoc :legal/topic (str/join " " (sort (map kw->s (:rule/topic r))))))))

(defn- verdict-entities [id jid]
  (for [[kind k] [["service" :jurisdiction/service-modes]
                  ["revenue" :jurisdiction/revenue-modes]]
        [mode entry] (get-in facts/catalog [jid k])]
    (cond-> {:db/id (id)
             :source/dataset dataset
             :legal/fact-kind "verdict"
             :legal/jurisdiction jid
             :legal/mode-kind kind
             :legal/mode (kw->s mode)
             :legal/verdict (kw->s (:verdict entry))
             :legal/basis (str/join " " (:basis entry))
             :legal/basis-count (count (:basis entry))}
      (:condition entry) (assoc :legal/condition (:condition entry)))))

(defn- gap-entities [id jid]
  (for [g (facts/known-gaps jid)]
    {:db/id (id)
     :source/dataset dataset
     :legal/fact-kind "known-gap"
     :legal/jurisdiction jid
     :legal/gap g}))

(defn datoms
  "The full projection as a tx-data vector."
  []
  (let [n (atom 0)
        id #(swap! n dec)]
    (vec (mapcat (fn [jid]
                   (concat (rule-entities id jid)
                           (verdict-entities id jid)
                           (gap-entities id jid)))
                 (facts/jurisdiction-ids)))))

(defn -main [& args]
  (let [path (or (first args) out-path)
        tx (datoms)]
    (io/make-parents path)
    (spit path (with-out-str
                 (println ";; GENERATED by `clojure -M:emit-datoms` — do not hand-edit.")
                 (println ";; Source of truth: src/legalsupport/facts.cljc")
                 (println)
                 (pp/pprint tx)))
    (println (str "wrote " path " — " (count tx) " entities across "
                  (count (facts/jurisdiction-ids)) " jurisdictions"))))
